### ISSUE TITLE
Error message with getAbapData()

### ISSUE THREAD

**Issue by JamesSwingler** [AfricaBirdData/ABAP#5]
![image](https://user-images.githubusercontent.com/72798491/151927586-9d8047c5-631c-41f7-b3b7-d0a20622d633.png)

This post is more to help others that run into this problem, rather than report an unresolved issue, but the above error message will appear if the version of ABAP or dependent libraries are outdated. So it is necessary to regularly update the relevant packages so as to circumvent this problem.

**Comment by patchcervan** [comment]
Thanks @JamesSwingler. That is very true! Keep the package updated. I must add that the problem in this case was that the API was unreachable, which sometimes happens. Version 0.0.3 would have thrown a slightly more informative message, but we should probably make it even more informative.

**Comment by patchcervan** [comment]
Actually, I think the error that is given now is informative enough and I would rather leave the original error message for debugging.
